/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdateRouteImport } from './routes/_update'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as UpdateSelfUpdateRouteImport } from './routes/_update/self-update'
import { Route as AuthTwoFactorRouteImport } from './routes/_auth/two-factor'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AppUploadRouteImport } from './routes/_app/upload'
import { Route as AppSetupRouteImport } from './routes/_app/setup'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMediaLibraryRouteImport } from './routes/_app/media-library'
import { Route as AppBackupRestoreRouteImport } from './routes/_app/backup-restore'
import { Route as AppAppsIndexRouteImport } from './routes/_app/apps/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppAppsGraphRouteImport } from './routes/_app/apps/graph'
import { Route as AppAppsCapacityRouteImport } from './routes/_app/apps/capacity'
import { Route as AppAppsAppNameRouteImport } from './routes/_app/apps/$appName'
import { Route as ApiMediaUploadHooksRouteImport } from './routes/api/media/upload/hooks'
import { Route as ApiHomelabLogsAppNameRouteImport } from './routes/api/homelab/logs.$appName'

const UpdateRoute = UpdateRouteImport.update({
  id: '/_update',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const UpdateSelfUpdateRoute = UpdateSelfUpdateRouteImport.update({
  id: '/self-update',
  path: '/self-update',
  getParentRoute: () => UpdateRoute,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaLibraryRoute = AppMediaLibraryRouteImport.update({
  id: '/media-library',
  path: '/media-library',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupRestoreRoute = AppBackupRestoreRouteImport.update({
  id: '/backup-restore',
  path: '/backup-restore',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsIndexRoute = AppAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppsGraphRoute = AppAppsGraphRouteImport.update({
  id: '/apps/graph',
  path: '/apps/graph',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsCapacityRoute = AppAppsCapacityRouteImport.update({
  id: '/apps/capacity',
  path: '/apps/capacity',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsAppNameRoute = AppAppsAppNameRouteImport.update({
  id: '/apps/$appName',
  path: '/apps/$appName',
  getParentRoute: () => AppRoute,
} as any)
const ApiMediaUploadHooksRoute = ApiMediaUploadHooksRouteImport.update({
  id: '/api/media/upload/hooks',
  path: '/api/media/upload/hooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomelabLogsAppNameRoute = ApiHomelabLogsAppNameRouteImport.update({
  id: '/api/homelab/logs/$appName',
  path: '/api/homelab/logs/$appName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/backup-restore': typeof AppBackupRestoreRoute
  '/media-library': typeof AppMediaLibraryRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/setup': typeof AppSetupRoute
  '/upload': typeof AppUploadRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/two-factor': typeof AuthTwoFactorRoute
  '/self-update': typeof UpdateSelfUpdateRoute
  '/apps/$appName': typeof AppAppsAppNameRoute
  '/apps/capacity': typeof AppAppsCapacityRoute
  '/apps/graph': typeof AppAppsGraphRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/apps/': typeof AppAppsIndexRoute
  '/api/homelab/logs/$appName': typeof ApiHomelabLogsAppNameRoute
  '/api/media/upload/hooks': typeof ApiMediaUploadHooksRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/backup-restore': typeof AppBackupRestoreRoute
  '/media-library': typeof AppMediaLibraryRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/setup': typeof AppSetupRoute
  '/upload': typeof AppUploadRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/two-factor': typeof AuthTwoFactorRoute
  '/self-update': typeof UpdateSelfUpdateRoute
  '/apps/$appName': typeof AppAppsAppNameRoute
  '/apps/capacity': typeof AppAppsCapacityRoute
  '/apps/graph': typeof AppAppsGraphRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/apps': typeof AppAppsIndexRoute
  '/api/homelab/logs/$appName': typeof ApiHomelabLogsAppNameRoute
  '/api/media/upload/hooks': typeof ApiMediaUploadHooksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_update': typeof UpdateRouteWithChildren
  '/_app/backup-restore': typeof AppBackupRestoreRoute
  '/_app/media-library': typeof AppMediaLibraryRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/setup': typeof AppSetupRoute
  '/_app/upload': typeof AppUploadRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/two-factor': typeof AuthTwoFactorRoute
  '/_update/self-update': typeof UpdateSelfUpdateRoute
  '/_app/': typeof AppIndexRoute
  '/_app/apps/$appName': typeof AppAppsAppNameRoute
  '/_app/apps/capacity': typeof AppAppsCapacityRoute
  '/_app/apps/graph': typeof AppAppsGraphRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/apps/': typeof AppAppsIndexRoute
  '/api/homelab/logs/$appName': typeof ApiHomelabLogsAppNameRoute
  '/api/media/upload/hooks': typeof ApiMediaUploadHooksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backup-restore'
    | '/media-library'
    | '/profile'
    | '/settings'
    | '/setup'
    | '/upload'
    | '/sign-in'
    | '/sign-up'
    | '/two-factor'
    | '/self-update'
    | '/apps/$appName'
    | '/apps/capacity'
    | '/apps/graph'
    | '/api/auth/$'
    | '/apps/'
    | '/api/homelab/logs/$appName'
    | '/api/media/upload/hooks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backup-restore'
    | '/media-library'
    | '/profile'
    | '/settings'
    | '/setup'
    | '/upload'
    | '/sign-in'
    | '/sign-up'
    | '/two-factor'
    | '/self-update'
    | '/apps/$appName'
    | '/apps/capacity'
    | '/apps/graph'
    | '/api/auth/$'
    | '/apps'
    | '/api/homelab/logs/$appName'
    | '/api/media/upload/hooks'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_update'
    | '/_app/backup-restore'
    | '/_app/media-library'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/setup'
    | '/_app/upload'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/two-factor'
    | '/_update/self-update'
    | '/_app/'
    | '/_app/apps/$appName'
    | '/_app/apps/capacity'
    | '/_app/apps/graph'
    | '/api/auth/$'
    | '/_app/apps/'
    | '/api/homelab/logs/$appName'
    | '/api/media/upload/hooks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  UpdateRoute: typeof UpdateRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHomelabLogsAppNameRoute: typeof ApiHomelabLogsAppNameRoute
  ApiMediaUploadHooksRoute: typeof ApiMediaUploadHooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_update': {
      id: '/_update'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_update/self-update': {
      id: '/_update/self-update'
      path: '/self-update'
      fullPath: '/self-update'
      preLoaderRoute: typeof UpdateSelfUpdateRouteImport
      parentRoute: typeof UpdateRoute
    }
    '/_auth/two-factor': {
      id: '/_auth/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup': {
      id: '/_app/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media-library': {
      id: '/_app/media-library'
      path: '/media-library'
      fullPath: '/media-library'
      preLoaderRoute: typeof AppMediaLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backup-restore': {
      id: '/_app/backup-restore'
      path: '/backup-restore'
      fullPath: '/backup-restore'
      preLoaderRoute: typeof AppBackupRestoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/': {
      id: '/_app/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppAppsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/apps/graph': {
      id: '/_app/apps/graph'
      path: '/apps/graph'
      fullPath: '/apps/graph'
      preLoaderRoute: typeof AppAppsGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/capacity': {
      id: '/_app/apps/capacity'
      path: '/apps/capacity'
      fullPath: '/apps/capacity'
      preLoaderRoute: typeof AppAppsCapacityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/$appName': {
      id: '/_app/apps/$appName'
      path: '/apps/$appName'
      fullPath: '/apps/$appName'
      preLoaderRoute: typeof AppAppsAppNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/media/upload/hooks': {
      id: '/api/media/upload/hooks'
      path: '/api/media/upload/hooks'
      fullPath: '/api/media/upload/hooks'
      preLoaderRoute: typeof ApiMediaUploadHooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/homelab/logs/$appName': {
      id: '/api/homelab/logs/$appName'
      path: '/api/homelab/logs/$appName'
      fullPath: '/api/homelab/logs/$appName'
      preLoaderRoute: typeof ApiHomelabLogsAppNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBackupRestoreRoute: typeof AppBackupRestoreRoute
  AppMediaLibraryRoute: typeof AppMediaLibraryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSetupRoute: typeof AppSetupRoute
  AppUploadRoute: typeof AppUploadRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAppsAppNameRoute: typeof AppAppsAppNameRoute
  AppAppsCapacityRoute: typeof AppAppsCapacityRoute
  AppAppsGraphRoute: typeof AppAppsGraphRoute
  AppAppsIndexRoute: typeof AppAppsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBackupRestoreRoute: AppBackupRestoreRoute,
  AppMediaLibraryRoute: AppMediaLibraryRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSetupRoute: AppSetupRoute,
  AppUploadRoute: AppUploadRoute,
  AppIndexRoute: AppIndexRoute,
  AppAppsAppNameRoute: AppAppsAppNameRoute,
  AppAppsCapacityRoute: AppAppsCapacityRoute,
  AppAppsGraphRoute: AppAppsGraphRoute,
  AppAppsIndexRoute: AppAppsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface UpdateRouteChildren {
  UpdateSelfUpdateRoute: typeof UpdateSelfUpdateRoute
}

const UpdateRouteChildren: UpdateRouteChildren = {
  UpdateSelfUpdateRoute: UpdateSelfUpdateRoute,
}

const UpdateRouteWithChildren =
  UpdateRoute._addFileChildren(UpdateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  UpdateRoute: UpdateRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHomelabLogsAppNameRoute: ApiHomelabLogsAppNameRoute,
  ApiMediaUploadHooksRoute: ApiMediaUploadHooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
