import { Badge } from "#/components/ui/badge";
import { Input } from "#/components/ui/input";
import { Label } from "#/components/ui/label";
import { Separator } from "#/components/ui/separator";
import { StepNavigation } from "../StepNavigation";
import type { SetupState } from "../SetupWizard";

interface SecretsStepProps {
	state: SetupState;
	updateState: (updates: Partial<SetupState>) => void;
	onComplete: () => void;
	onBack: () => void;
}

// Placeholder secret definitions — will be driven by the app registry later
interface SecretField {
	app: string;
	appDisplayName: string;
	key: string;
	label: string;
	description: string;
	required: boolean;
	sensitive: boolean;
	autoGenerated?: boolean;
	defaultValue?: string;
}

function getSecretsForApps(selectedApps: string[]): SecretField[] {
	const secrets: SecretField[] = [];

	if (selectedApps.includes("duckdns")) {
		secrets.push(
			{
				app: "duckdns",
				appDisplayName: "DuckDNS",
				key: "DUCKDNS_SUBDOMAINS",
				label: "Subdomains",
				description: "Your DuckDNS subdomain (e.g. myhomelab)",
				required: true,
				sensitive: false,
			},
			{
				app: "duckdns",
				appDisplayName: "DuckDNS",
				key: "DUCKDNS_TOKEN",
				label: "Token",
				description: "Your DuckDNS authentication token",
				required: true,
				sensitive: true,
			},
		);
	}

	if (selectedApps.includes("wireguard")) {
		secrets.push(
			{
				app: "wireguard",
				appDisplayName: "WireGuard",
				key: "WG_SERVERURL",
				label: "Server URL",
				description: "Public URL or IP for WireGuard server",
				required: true,
				sensitive: false,
			},
			{
				app: "wireguard",
				appDisplayName: "WireGuard",
				key: "WG_PEERS",
				label: "Peers",
				description: "Number of VPN peers to generate",
				required: false,
				sensitive: false,
				defaultValue: "3",
			},
		);
	}

	if (selectedApps.includes("yourspotify")) {
		secrets.push(
			{
				app: "yourspotify",
				appDisplayName: "Your Spotify",
				key: "SPOTIFY_CLIENT_ID",
				label: "Client ID",
				description: "Spotify API client ID",
				required: true,
				sensitive: true,
			},
			{
				app: "yourspotify",
				appDisplayName: "Your Spotify",
				key: "SPOTIFY_CLIENT_SECRET",
				label: "Client Secret",
				description: "Spotify API client secret",
				required: true,
				sensitive: true,
			},
		);
	}

	return secrets;
}

export function SecretsStep({
	state,
	updateState,
	onComplete,
	onBack,
}: SecretsStepProps) {
	const secretFields = getSecretsForApps(state.selectedApps);

	if (secretFields.length === 0) {
		return (
			<div>
				<h2 className="font-display text-2xl font-bold tracking-tight">
					Secrets & API Keys
				</h2>
				<p className="mt-2 text-muted-foreground">
					None of your selected apps require secrets. You're all set!
				</p>
				<StepNavigation onBack={onBack} onNext={onComplete} />
			</div>
		);
	}

	// Group by app
	const grouped = secretFields.reduce<Record<string, SecretField[]>>(
		(acc, field) => {
			if (!acc[field.app]) acc[field.app] = [];
			acc[field.app].push(field);
			return acc;
		},
		{},
	);

	const updateSecret = (key: string, value: string) => {
		updateState({ secrets: { ...state.secrets, [key]: value } });
	};

	const requiredMissing = secretFields.some(
		(f) => f.required && !state.secrets[f.key]?.trim(),
	);

	return (
		<div>
			<h2 className="font-display text-2xl font-bold tracking-tight">
				Secrets & API Keys
			</h2>
			<p className="mt-2 text-muted-foreground">
				Enter the required credentials for your selected apps.
			</p>

			<div className="mt-8 space-y-8">
				{Object.entries(grouped).map(([appName, fields], groupIdx) => (
					<div key={appName}>
						{groupIdx > 0 && <Separator className="mb-8" />}
						<h3 className="mb-4 text-sm font-semibold">
							{fields[0].appDisplayName}
						</h3>
						<div className="space-y-4">
							{fields.map((field) => (
								<div key={field.key} className="space-y-1.5">
									<Label
										htmlFor={field.key}
										className="flex items-center gap-2"
									>
										{field.label}
										{field.required && (
											<span className="text-destructive">*</span>
										)}
										{field.autoGenerated && (
											<Badge variant="outline" className="text-[10px]">
												Auto-generated
											</Badge>
										)}
									</Label>
									<Input
										id={field.key}
										type={field.sensitive ? "password" : "text"}
										value={
											state.secrets[field.key] ??
											field.defaultValue ??
											""
										}
										onChange={(e) =>
											updateSecret(field.key, e.target.value)
										}
										placeholder={field.description}
									/>
									<p className="text-xs text-muted-foreground">
										{field.description}
									</p>
								</div>
							))}
						</div>
					</div>
				))}
			</div>

			<StepNavigation
				onBack={onBack}
				onNext={onComplete}
				nextDisabled={requiredMissing}
			/>
		</div>
	);
}
